### PR TITLE
Ignore shutdown exits

### PR DESCRIPTION
**Pull request by essen**
Hey Roberto, long time no speak! I'm cleaning up my logs and these two commits would help immensely.

### CODE REVIEW

**Comment by ostinelli** [comment]
Ok will merge in. One question: why do you need the LF in `error_logger`, are you using it with lager?

**Comment by essen** [comment]
Seems to be the reason yes.

**Comment by ostinelli** [comment]
Ok. Merged, thank you.

**Comment by essen** [comment]
Thanks!

**Pull request merged**
