### PR TITLE
Added function to get all registered Process Groups

### PR DESCRIPTION
**Pull request by veedo**
This function is useful when you want to iterate over all the groups your application is using. 

Some examples:
- Unsubscribe to all topics in a pub-sub system
- Connecting to application from a "debug console"
- Sending a message to all groups

### CODE REVIEW

**Comment by ostinelli** [comment]
Hello, thank you for your contribution! As per the README, please squash with `git rebase -i` for review.

**Comment by veedo** [comment]
I'm a little confused, if you don't mind clarifying.

> * Only the 2 nodes is necessary

I should delete the single node test?

> * Please review your variable naming (you use RemotePidRegRemote but it's not joined on remote)

https://github.com/veedo/syn/blob/get_group_names/test/syn_groups_SUITE.erl#L692 is calling join from the remote node? Or do you mean something else?

Added a check to make sure the list is the right length.

**Comment by yrashk** [comment]
@ostinelli @veedo I am interested in this functionality. Any plans to go further on this, or should I send a new PR?

**Comment by veedo** [comment]
> 
> 
> @ostinelli @veedo I am interested in this functionality. Any plans to go further on this, or should I send a new PR?

Once there is some clarification on my last comment, I can make any necessary changes and it can get merged.

The code in my PR is tested and I'm using it in production without issues so far.
You can always use my branch for now or implement the function outside the library.
Relevant code: https://github.com/veedo/syn/blob/f155c905f5b2e6806a0e065f47e61b566a9da713/src/syn_groups.erl#L120-L128

**Comment by ostinelli** [comment]
Thank you, merged.

**Pull request merged**
