### PR TITLE
Fix syn groups leaving bug

### PR DESCRIPTION
**Pull request by seb3s**
Fix issue #24

### CODE REVIEW

**Comment by ostinelli** [comment]
Thank you, as per README I'll need a test for this before it gets merged in.

**Comment by ostinelli** [comment]
Thank you for input. Please squash the commits and I'll merge in!

**Comment by seb3s** [comment]
Hello,
I've never done that before, this is the first time, so I hope I did it right :-)

**Comment by seb3s** [comment]
Hi Roberto,
is everything ok ?
Cheers,
Sébastien.

**Comment by ostinelli** [comment]
Thank you, merged in.

**Pull request merged**
